# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syslog-health-monitor.fullname" . }}
  labels:
    {{- include "syslog-health-monitor.labels" . | nindent 4 }}
data:
  # This ConfigMap is currently minimal as primary configuration is passed
  # via command-line arguments in the DaemonSet, sourced from values.yaml.
  # It can be extended in the future if needed for more complex configurations
  # or scripts.
  log_check_definitions.yaml: |
    checks:
      - name: "SysLogsXIDError"
      {{- if .Values.global.kata.enabled }}
        tags:
          - "-u containerd.service"
        {{- end }}
        journalPath: "/nvsentinel/var/log/journal/"

      {{- if not .Values.global.kata.enabled }}
      - name: "SysLogsSXIDError"
        journalPath: "/nvsentinel/var/log/journal/"
      {{- end }}
